/* Generated By:JavaCC: Do not edit this line. AssignmentConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AssignmentConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LEFTBRACKET = 1;
  /** RegularExpression Id. */
  int RIGHTBRACKET = 2;
  /** RegularExpression Id. */
  int LEFTCURLYBRACKET = 3;
  /** RegularExpression Id. */
  int RIGHTCURLYBRACKET = 4;
  /** RegularExpression Id. */
  int SPACE = 5;
  /** RegularExpression Id. */
  int DEF = 6;
  /** RegularExpression Id. */
  int MAIN = 7;
  /** RegularExpression Id. */
  int FUNCNAME = 8;
  /** RegularExpression Id. */
  int PARAMETER = 9;
  /** RegularExpression Id. */
  int FUNCBODY = 10;
  /** RegularExpression Id. */
  int EOL = 11;
  /** RegularExpression Id. */
  int ADDITION = 12;
  /** RegularExpression Id. */
  int MULTIPLICATION = 13;
  /** RegularExpression Id. */
  int UPPERCHAR = 14;
  /** RegularExpression Id. */
  int LOWERCHAR = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\" \"",
    "\"DEF\"",
    "\"MAIN\"",
    "<FUNCNAME>",
    "<PARAMETER>",
    "\"x+4\"",
    "<EOL>",
    "\"+\"",
    "\"*\"",
    "<UPPERCHAR>",
    "<LOWERCHAR>",
    "<DIGIT>",
  };

}
